auto: true

markdown: rdiscount
pygments: true
paginate: 6
permalink: /:title
baseurl: /

title: BarretLee's Blog
url: http://hustskyking.github.io
repo: http://qianduannotes.duapp.com/github/barretlee.github.com
feed: /atom.xml
highlight: light
author_name: Barret Lee
author_info: <a href="http://hustskyking.github.com">BarretLee</a>
